# Generated by Django 2.2.5 on 2020-03-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classwork_app', '0003_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
