# Generated by Django 2.2.5 on 2020-03-16 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classwork_app', '0004_auto_20200316_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='title',
            new_name='abt_title',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='img',
            new_name='profile',
        ),
    ]
